version: '3'
services:
  mysql:
    container_name: "db"
    image: mysql:8.0.23
    volumes:
      - ./DB/docker/db/data:/var/lib/mysql
      - ./DB/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: test
  be:
    container_name: "be"
    build:
      context: ./
      dockerfile: ./BE/docker/app/Dockerfile
    depends_on:
      - mysql
    environment:
      - ENV_MODE=dev
      - BE_PORT=8000
      - PRODUCT_CODE='BTC_JPY'
      - API_BASE_URL='http://be:8000/'
      - CRYPTOWATCH_URL='https://api.cryptowat.ch/markets/bitflyer/btcjpy/ohlc'
    ports:
      - 8000:8000
    working_dir: /usr/src/app/BE
    volumes:
      - ./:/usr/src/app
    command: realize start --run
    tty: true
    stdin_open: true
  fe:
    container_name: "fe"
    build:
      context: ./
      dockerfile: ./FE/Dockerfile
    command: ['/bin/bash', '-c', 'NUXT_HOST=0.0.0.0 yarn run dev']
    working_dir: /usr/src/app/FE
    volumes:
      - ./:/usr/src/app
    ports:
      - 8001:3000
    environment:
      TZ: Asia/Tokyo
      API_BASE_URL: 'http://be:8000/'
    depends_on:
      - be
    environment:
      - HOST=0.0.0.0
      - API_BASE_URL='http://be:8000/'
